const A=document.getElementById("app");let E=[],J=[];
async function data(){E=await fetch("/api/editors").then(x=>x.json());J=await fetch("/api/jobs").then(x=>x.json());home()}
function home(){A.innerHTML=`<div class=wrap><section class=hero><h1>Editors खोजें • Jobs पाएँ • काम करवाएँ</h1><p>Clients और professional editors को एक जगह जोड़ने वाला platform.</p><button class=primary onclick="jobs()">नई Jobs देखें</button> <button onclick="register()">Editor बनें</button></section><div class=grid><div class=card><h2>🎬 Editor Profiles</h2><p>Skills और portfolio देखकर editor चुनें.</p></div><div class=card><h2>💼 Jobs</h2><p>नई editing jobs post करें और apply करें.</p></div><div class=card><h2>⭐ Ratings</h2><p>अच्छे editors की पहचान आसान होगी.</p></div></div></div>`}
function editors(){A.innerHTML=`<div class=wrap><h2>🎬 Editors</h2><div class=grid>${E.map(e=>`<div class=card><h2>${e.name} ✅</h2><p class=muted>${e.bio||"Professional Editor"}</p><p>${(e.skills||"").split(",").map(s=>`<span class=pill>${s}</span>`).join("")}</p><b>Portfolio</b><p>${(e.portfolio||"").split("|").map(s=>`<span class=pill>${s}</span>`).join("")}</p><button class=primary onclick="alert('Contact request sent to ${e.name}')">Contact / Hire</button></div>`).join("")}</div></div>`}
function jobs(){A.innerHTML=`<div class=wrap><button class=primary onclick="post()">+ Post Job</button><h2>💼 Latest Jobs</h2><div class=grid>${J.length?J.map(j=>`<div class=card><h2>${j.title}</h2><p class=muted>${j.category} • Deadline: ${j.deadline}</p><p>${j.description}</p><b>Budget: ₹${j.budget}</b><br><button class=primary onclick="apply(${j.id})">Apply Now</button></div>`).join(""):`<div class=card>अभी कोई Job नहीं है।</div>`}</div></div>`}
function register(){A.innerHTML=`<div class=wrap><div class=form><h2>👤 Create Profile</h2><input id=n placeholder="Name"><input id=e placeholder="Email"><select id=r><option value=editor>Editor</option><option value=client>Client</option></select><input id=s placeholder="Skills"><textarea id=b placeholder="Bio"></textarea><input id=p placeholder="Portfolio items, | से अलग करें"><button class=primary onclick="saveUser()">Create Account</button><p id=m></p></div></div>`}
async function saveUser(){let x=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:n.value,email:e.value,role:r.value,skills:s.value,bio:b.value,portfolio:p.value})});m.textContent=x.ok?"Profile created successfully!":"Email already registered.";data()}
function post(){A.innerHTML=`<div class=wrap><div class=form><h2>➕ Post a Job</h2><input id=t placeholder="Job Title"><select id=c><option>Video Editing</option><option>Reels</option><option>YouTube</option><option>Thumbnail</option><option>Wedding</option><option>VFX</option></select><input id=bu placeholder="Budget"><input id=d placeholder="Deadline"><textarea id=de placeholder="काम की जानकारी"></textarea><button class=primary onclick="saveJob()">Publish Job</button><p id=m></p></div></div>`}
async function saveJob(){await fetch("/api/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:t.value,category:c.value,budget:bu.value,deadline:d.value,description:de.value,client_id:1})});data()}
async function apply(id){if(!E.length)return alert("पहले Editor profile बनाइए.");await fetch("/api/apply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job_id:id,editor_id:E[0].id,message:"I want to apply for this job."})});alert("Application submitted successfully!")}
data();